/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SSHLAUNCHER_PRIVATE_H
#define SSHLAUNCHER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.0.3"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	0
#define VER_BUILD	3
#define COMPANY_NAME	"TWXH"
#define FILE_VERSION	"1.2.0.3"
#define FILE_DESCRIPTION	"SSHLauncher"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"SSHLauncher.exe"
#define PRODUCT_NAME	"SSHLauncher"
#define PRODUCT_VERSION	"1.2.0.3"

#endif /*SSHLAUNCHER_PRIVATE_H*/
